package com.zs.entity;

import java.math.BigDecimal;
import java.util.Date;

public class BigPagCentersendScan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIG_PAG_CENTERSEND_SCAN.ID
     *
     * @mbggenerated
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIG_PAG_CENTERSEND_SCAN.BIG_NO
     *
     * @mbggenerated
     */
    private String bigNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIG_PAG_CENTERSEND_SCAN.SCAN_TYPE
     *
     * @mbggenerated
     */
    private String scanType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIG_PAG_CENTERSEND_SCAN.PAG_POINT_CODE
     *
     * @mbggenerated
     */
    private String pagPointCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIG_PAG_CENTERSEND_SCAN.PAG_POINT_NAME
     *
     * @mbggenerated
     */
    private String pagPointName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIG_PAG_CENTERSEND_SCAN.PAG_SEND_TIME
     *
     * @mbggenerated
     */
    private Date pagSendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIG_PAG_CENTERSEND_SCAN.NUM
     *
     * @mbggenerated
     */
    private BigDecimal num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIG_PAG_CENTERSEND_SCAN.NEXT_POINT_CODE
     *
     * @mbggenerated
     */
    private String nextPointCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIG_PAG_CENTERSEND_SCAN.NEXT_POINT_NAME
     *
     * @mbggenerated
     */
    private String nextPointName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIG_PAG_CENTERSEND_SCAN.MAN_NO
     *
     * @mbggenerated
     */
    private String manNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIG_PAG_CENTERSEND_SCAN.MAN_NAME
     *
     * @mbggenerated
     */
    private String manName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIG_PAG_CENTERSEND_SCAN.IS_DELETE
     *
     * @mbggenerated
     */
    private BigDecimal isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BIG_PAG_CENTERSEND_SCAN.DATA_TIME
     *
     * @mbggenerated
     */
    private Date dataTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIG_PAG_CENTERSEND_SCAN.ID
     *
     * @return the value of BIG_PAG_CENTERSEND_SCAN.ID
     *
     * @mbggenerated
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIG_PAG_CENTERSEND_SCAN.ID
     *
     * @param id the value for BIG_PAG_CENTERSEND_SCAN.ID
     *
     * @mbggenerated
     */
    public BigPagCentersendScan setId(BigDecimal id) {
        this.id = id;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIG_PAG_CENTERSEND_SCAN.BIG_NO
     *
     * @return the value of BIG_PAG_CENTERSEND_SCAN.BIG_NO
     *
     * @mbggenerated
     */
    public String getBigNo() {
        return bigNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIG_PAG_CENTERSEND_SCAN.BIG_NO
     *
     * @param bigNo the value for BIG_PAG_CENTERSEND_SCAN.BIG_NO
     *
     * @mbggenerated
     */
    public BigPagCentersendScan setBigNo(String bigNo) {
        this.bigNo = bigNo == null ? null : bigNo.trim();
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIG_PAG_CENTERSEND_SCAN.SCAN_TYPE
     *
     * @return the value of BIG_PAG_CENTERSEND_SCAN.SCAN_TYPE
     *
     * @mbggenerated
     */
    public String getScanType() {
        return scanType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIG_PAG_CENTERSEND_SCAN.SCAN_TYPE
     *
     * @param scanType the value for BIG_PAG_CENTERSEND_SCAN.SCAN_TYPE
     *
     * @mbggenerated
     */
    public BigPagCentersendScan setScanType(String scanType) {
        this.scanType = scanType == null ? null : scanType.trim();
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIG_PAG_CENTERSEND_SCAN.PAG_POINT_CODE
     *
     * @return the value of BIG_PAG_CENTERSEND_SCAN.PAG_POINT_CODE
     *
     * @mbggenerated
     */
    public String getPagPointCode() {
        return pagPointCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIG_PAG_CENTERSEND_SCAN.PAG_POINT_CODE
     *
     * @param pagPointCode the value for BIG_PAG_CENTERSEND_SCAN.PAG_POINT_CODE
     *
     * @mbggenerated
     */
    public BigPagCentersendScan setPagPointCode(String pagPointCode) {
        this.pagPointCode = pagPointCode == null ? null : pagPointCode.trim();
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIG_PAG_CENTERSEND_SCAN.PAG_POINT_NAME
     *
     * @return the value of BIG_PAG_CENTERSEND_SCAN.PAG_POINT_NAME
     *
     * @mbggenerated
     */
    public String getPagPointName() {
        return pagPointName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIG_PAG_CENTERSEND_SCAN.PAG_POINT_NAME
     *
     * @param pagPointName the value for BIG_PAG_CENTERSEND_SCAN.PAG_POINT_NAME
     *
     * @mbggenerated
     */
    public BigPagCentersendScan setPagPointName(String pagPointName) {
        this.pagPointName = pagPointName == null ? null : pagPointName.trim();
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIG_PAG_CENTERSEND_SCAN.PAG_SEND_TIME
     *
     * @return the value of BIG_PAG_CENTERSEND_SCAN.PAG_SEND_TIME
     *
     * @mbggenerated
     */
    public Date getPagSendTime() {
        return pagSendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIG_PAG_CENTERSEND_SCAN.PAG_SEND_TIME
     *
     * @param pagSendTime the value for BIG_PAG_CENTERSEND_SCAN.PAG_SEND_TIME
     *
     * @mbggenerated
     */
    public BigPagCentersendScan setPagSendTime(Date pagSendTime) {
        this.pagSendTime = pagSendTime;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIG_PAG_CENTERSEND_SCAN.NUM
     *
     * @return the value of BIG_PAG_CENTERSEND_SCAN.NUM
     *
     * @mbggenerated
     */
    public BigDecimal getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIG_PAG_CENTERSEND_SCAN.NUM
     *
     * @param num the value for BIG_PAG_CENTERSEND_SCAN.NUM
     *
     * @mbggenerated
     */
    public BigPagCentersendScan setNum(BigDecimal num) {
        this.num = num;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIG_PAG_CENTERSEND_SCAN.NEXT_POINT_CODE
     *
     * @return the value of BIG_PAG_CENTERSEND_SCAN.NEXT_POINT_CODE
     *
     * @mbggenerated
     */
    public String getNextPointCode() {
        return nextPointCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIG_PAG_CENTERSEND_SCAN.NEXT_POINT_CODE
     *
     * @param nextPointCode the value for BIG_PAG_CENTERSEND_SCAN.NEXT_POINT_CODE
     *
     * @mbggenerated
     */
    public BigPagCentersendScan setNextPointCode(String nextPointCode) {
        this.nextPointCode = nextPointCode == null ? null : nextPointCode.trim();
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIG_PAG_CENTERSEND_SCAN.NEXT_POINT_NAME
     *
     * @return the value of BIG_PAG_CENTERSEND_SCAN.NEXT_POINT_NAME
     *
     * @mbggenerated
     */
    public String getNextPointName() {
        return nextPointName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIG_PAG_CENTERSEND_SCAN.NEXT_POINT_NAME
     *
     * @param nextPointName the value for BIG_PAG_CENTERSEND_SCAN.NEXT_POINT_NAME
     *
     * @mbggenerated
     */
    public BigPagCentersendScan setNextPointName(String nextPointName) {
        this.nextPointName = nextPointName == null ? null : nextPointName.trim();
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIG_PAG_CENTERSEND_SCAN.MAN_NO
     *
     * @return the value of BIG_PAG_CENTERSEND_SCAN.MAN_NO
     *
     * @mbggenerated
     */
    public String getManNo() {
        return manNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIG_PAG_CENTERSEND_SCAN.MAN_NO
     *
     * @param manNo the value for BIG_PAG_CENTERSEND_SCAN.MAN_NO
     *
     * @mbggenerated
     */
    public BigPagCentersendScan setManNo(String manNo) {
        this.manNo = manNo == null ? null : manNo.trim();
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIG_PAG_CENTERSEND_SCAN.MAN_NAME
     *
     * @return the value of BIG_PAG_CENTERSEND_SCAN.MAN_NAME
     *
     * @mbggenerated
     */
    public String getManName() {
        return manName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIG_PAG_CENTERSEND_SCAN.MAN_NAME
     *
     * @param manName the value for BIG_PAG_CENTERSEND_SCAN.MAN_NAME
     *
     * @mbggenerated
     */
    public BigPagCentersendScan setManName(String manName) {
        this.manName = manName == null ? null : manName.trim();
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIG_PAG_CENTERSEND_SCAN.IS_DELETE
     *
     * @return the value of BIG_PAG_CENTERSEND_SCAN.IS_DELETE
     *
     * @mbggenerated
     */
    public BigDecimal getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIG_PAG_CENTERSEND_SCAN.IS_DELETE
     *
     * @param isDelete the value for BIG_PAG_CENTERSEND_SCAN.IS_DELETE
     *
     * @mbggenerated
     */
    public BigPagCentersendScan setIsDelete(BigDecimal isDelete) {
        this.isDelete = isDelete;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BIG_PAG_CENTERSEND_SCAN.DATA_TIME
     *
     * @return the value of BIG_PAG_CENTERSEND_SCAN.DATA_TIME
     *
     * @mbggenerated
     */
    public Date getDataTime() {
        return dataTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BIG_PAG_CENTERSEND_SCAN.DATA_TIME
     *
     * @param dataTime the value for BIG_PAG_CENTERSEND_SCAN.DATA_TIME
     *
     * @mbggenerated
     */
    public BigPagCentersendScan setDataTime(Date dataTime) {
        this.dataTime = dataTime;
        return this;
    }
}
