package com.zs.dao;

import com.zs.entity.BigPagCentersendScan;
import java.math.BigDecimal;

public interface BigPagCentersendScanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIG_PAG_CENTERSEND_SCAN
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIG_PAG_CENTERSEND_SCAN
     *
     * @mbggenerated
     */
    int insert(BigPagCentersendScan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIG_PAG_CENTERSEND_SCAN
     *
     * @mbggenerated
     */
    int insertSelective(BigPagCentersendScan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIG_PAG_CENTERSEND_SCAN
     *
     * @mbggenerated
     */
    BigPagCentersendScan selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIG_PAG_CENTERSEND_SCAN
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BigPagCentersendScan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIG_PAG_CENTERSEND_SCAN
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BigPagCentersendScan record);
}