package com.zs.dao;

import com.zs.entity.BigSendScan;
import java.math.BigDecimal;

public interface BigSendScanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIG_SEND_SCAN
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIG_SEND_SCAN
     *
     * @mbggenerated
     */
    int insert(BigSendScan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIG_SEND_SCAN
     *
     * @mbggenerated
     */
    int insertSelective(BigSendScan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIG_SEND_SCAN
     *
     * @mbggenerated
     */
    BigSendScan selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIG_SEND_SCAN
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BigSendScan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BIG_SEND_SCAN
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BigSendScan record);
}